client_id: 3MVG9sG9Z3Q1RlbcubFxMYFf1weHuJ8PXijSAoNcd_hZ2BAxHM8P9FMIAFrdhRA_YnM0R8TSuqJevVUQch4Bl
client_secret: 9214423190518390927
username: aaron@productschool.com
password: Frontone22!
debuggin: false
